name: Publish Docs
on:
  push:
    branches:
      - main
jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install Build Requirements
        run: pip install -r requirements.txt
      - name: Deploy Docs
        run: mkdocs gh-deploy --force
